### ISSUE TITLE
image

### ISSUE THREAD

**Issue by kangjimin1** [iank1m/OSS-Project_pygame#3]
![82FF8634-7316-42CE-A225-D7870C257A06](https://github.com/iank1m/OSS-Project_pygame/assets/107349918/6be70d80-2528-41be-a4e4-675005bab4ca)

**Comment by iank1m** [comment]
오 화질 안깨졌네용. 이거 쓰면 될 것 같은데 이거랑 똑같은 해상도 파일이 레포에 등록 돼있으니까 이슈 처리해주세용 !
